### ISSUE TITLE
TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded

### ISSUE THREAD

**Issue by jedcua** [agarrec-vivlio/export-code-pdf-cli#1]
Hello! I tried to generate a pdf for a Java based project, with the command below

```
$ export-code-pdf-cli --regex ".*\\.(groovy|java|js|json|md|properties|sh|sql|wsdl|xjb|xml|xsd|yaml|yml)$"
```

However I got an error below

```
✖ Error during processing.
Error: TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded
    at Object.waitWithTimeout (/home/jed/Applications/node-v14.20.0-linux-x64/lib/node_modules/export-code-pdf-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/helper.js:224:26)
    at Page.createPDFStream (/home/jed/Applications/node-v14.20.0-linux-x64/lib/node_modules/export-code-pdf-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2045:49)
    at Page.pdf (/home/jed/Applications/node-v14.20.0-linux-x64/lib/node_modules/export-code-pdf-cli/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2057:37)
    at /home/jed/Applications/node-v14.20.0-linux-x64/lib/node_modules/export-code-pdf-cli/src/index.js:106:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

If it helps, my node version is `v14.20.0` on Linux.

Can you check what went wrong? Cool project btw!

**Comment by agarrec-vivlio** [comment]
Hey! Thanks for trying out the project ! 

The error you're seeing (`TimeoutError: waiting for Page.printToPDF failed: timeout 30000ms exceeded`) usually happens when Puppeteer takes longer than expected to generate the PDF due to the amount of content or system performance.

### Solution:
To fix this, you can **increase the timeout** or **disable it entirely** by setting the `timeout` option to `0`. Here's what you can do:

1. **Locate the `page.pdf()` call in the source code** (`/home/jed/Applications/node-v14.20.0-linux-x64/lib/node_modules/export-code-pdf-cli/src/index.js`).
2. **Update the `page.pdf()` call** like this:

```javascript
await page.pdf({
  path: options.output,
  format: 'A4',
  printBackground: true,
  timeout: 0 // Disable timeout
});
```

This will allow Puppeteer to wait as long as it needs to generate the PDF, which should resolve the timeout issue you're facing, especially when handling large projects.

Let me know if that works for you!

**Comment by jedcua** [comment]
Hello! Disabling the timeout worked! 

May I suggest as an improvement to have a way to define/override the default timeout? Maybe something like:
```
$  export-code-pdf-cli --timeout 0
```

Again, thanks for your help!
